### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gclenaghan**

### CODE REVIEW

**Comment by gclenaghan** [comment]
I guess I don't have write access?

**Comment by cswiercz** [comment]
I'm not going to enable push/pull access yet until I discuss the "standard git workflow":
1. clone the repo
2. make changes
3. push commits to your remote
4. submit pull request to other person's repo
5. other person accepts changes and pulls

Git is meant to be pull-centric, not push centric...

...however, I think that once we talk about this next week we can open up some / all repos to be pushable by anyone in the group. I dunno...thoughts?

**Comment by gclenaghan** [comment]
Sure, I just meant what I wrote as a git crash course, not a github crash course (the push command should be to your own repos). There is probably more to say there.

**Comment by cswiercz** [comment]
I'm still figuring out "Github Organizations" but I think I figured out the permissions issue.

Different "teams" can manage different sets of repositories. So currently there are "Owners" repos and "Members" repos. There are three different permissions settings to choose from for each of these teams:
- **Read Access** - This team will be able to view and clone its repositories.
- **Write Access** - This team will be able to read its repositories, as well as push to them.
- **Admin Access** - This team will be able to push/pull to its repositories, as well as add other collaborators to them.

I currently set "Members" to **Write Access** so any repo created by a member and be pushed to. This is definitely outside the normal Git workflow model.

I think the problem here is that I created `git-tips` as an owner, not a member.

I haven't decided what would be the best way to have Git / Github newbies interact with the organization. Initially, I thought that full Read / Write access would make it easy. But now I'm wondering if that would cause too many people to step on each other's toes.

**Comment by cswiercz** [comment]
_Update:_ in the repo's settings I can specify which teams have push access. I've added "Members" to `git-tips`.

**Pull request merged**
